version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
  lint_unit_test_coverage:
    working_directory: ~/repo
    docker:
      - image: circleci/buildpack-deps:18.04-browsers
jobs:
  lint_unit_test_coverage:
    working_directory: ~/repo
    docker:
      - image: circleci/buildpack-deps:18.04-browsers
    steps:
      - checkout
      - install_container_dependencies
      - run:
          name: Install dependencies
          command: bash -i -c 'npm ci'
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build
          command: npm run build.prod
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  build-and-test:
    jobs:
      - build-and-test

jobs:


  upload_to_s3:
    working_directory: ~/repo
    docker:
      - image: circleci/python:2.7
    parameters:
      aws_bucket:
        type: string
        default: "${AWS_BUCKET}"
    steps:
      - when:
          condition: <<parameters.aws_bucket>>
          steps:
            - get_workspace
            - install_container_dependencies
            # Build again for the upload to s3
            # TODO: https://gui.dockstore.org/${CIRCLE_TAG:-$CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7) can probably be made into a bash/circle-ci variable.
            - run:
                name: Swap for CDN paths
                command: bash -i -c "find src \( -iname '*.html' -o -iname '*.ts' -o -iname '*.json' \) -exec sed -i 's~\(\.\./\)\+assets/~https://gui\.dockstore\.org/${CIRCLE_TAG:-$CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)/assets/~g' {} +"
            - run:
                name: Build
                command: bash -i -c 'npm run build.prod -- --deploy-url https://gui.dockstore.org/${CIRCLE_TAG:-$CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)/'
            # Copy to a versioned folder
            - aws-s3/copy:
                from: dist
                to: 's3://${AWS_BUCKET}/${CIRCLE_TAG:-$CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)'
                arguments: |
                  --recursive \
                  --exclude index.html
            - aws-s3/copy:
                from: dist/index.html
                to: 's3://${AWS_BUCKET}/${CIRCLE_TAG-$CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)/index.html'
                arguments: |
                  --cache-control max-age=0

workflows:
  version: 2
  everything:
    jobs:
      #      # Add the tags filter to all jobs so they will run before upload_to_s3
      - lint_unit_test_coverage:
          filters:
            tags:
              only: /.*/
      - licenses_test:
          filters:
            tags:
              only: /.*/
      - integration_test_1:
          filters:
            tags:
              only: /.*/
          requires:
            - lint_unit_test_coverage
            - licenses_test
      - integration_test_2:
          filters:
            tags:
              only: /.*/
          requires:
            - lint_unit_test_coverage
            - licenses_test
      - integration_test_3:
          filters:
            tags:
              only: /.*/
          requires:
            - lint_unit_test_coverage
            - licenses_test
      # Upload builds for tags and branches to s3.
      - upload_to_s3:
          requires:
            - integration_test_1
            - integration_test_2
            - integration_test_3
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - check_build_develop:
          requires:
            - upload_to_s3
          filters:
            branches:
              only: /^develop/

  nightly:
    triggers:
      - schedule:
          cron: "0 11 * * *" # This is 4am PDT / 3am PST
          filters:
            branches:
              only:
                - develop
    jobs:
      - uptime_monitor

commands:
  install_container_dependencies:
    steps:
      - run:
          name: Install java
          command: |
            sudo apt update -y
            sudo apt install openjdk-11-jre -yq
      - run:
          name: Install npm
          command: |
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            bash -i -c 'nvm install'
  get_workspace:
    steps:
      - attach_workspace:
          at: .
  upload_artifacts:
    steps:
      - store_test_results:
          path: integration-tests/test-results
      - store_artifacts:
          path: integration-tests/test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  setup_integration_test:
    steps:
      - get_workspace
      - install_container_dependencies
      - run:
          name: Install postgresql client
          command: sudo apt install -y postgresql-client || true
      - run:
          name: Install cypress dependencies
          command: sudo apt install libgtk2.0-0 -yq
      - run:
          name: Prepare webservice
          command: bash -i -c 'npm run webservice'
      - run:
          name: Install nginx
          command: sudo apt install -y nginx || true
      - run:
          name: Prepapre nginx config
          command: sed "s%REPLACEME%`pwd`%" .circleci/nginx.conf.tmpl > .circleci/nginx.conf
      - run:
          name: Run nginx
          command: sudo nginx -c `pwd`/.circleci/nginx.conf
          background: true
      - run:
          name: Run webservice
          command: java -jar dockstore-webservice.jar server travisci/web.yml 1>/dev/null
          background: true
      - run: mkdir -p integration-tests/test-results/junit
      - run:
          name: Wait for services
          command: bash scripts/wait-for.sh
